<script>
/*****************************************************************
 ** 
 *****************************************************************/

function geod_login ( form ) {
// --------------------------------------------------
    return false;
}

</script>

  <table id="file-list" cellpadding="0" cellspacing="0" border="0"  style="padding:0px;width:100%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Created</th>
        <th>Nodes</th>
      </tr>
    </thead>

    <tbody>

      <tr>
        <td>Hoserpla</td>
        <td>1235-12-34</td>
        <td>123</td>
      </tr>

    </tbody>
  </table>

  <script type="text/javascript">
    $(function(){
      $("#file-list").dataTable({
      });
    });
  </script>
