<script>
/*****************************************************************
 ** To gain access to stored routes and waypoints, a user must
 ** identify themselves to the server. We'll handle that here.
 *****************************************************************/
<?
  require Geo::Dashboard::User::Settings;
  my $set_rec = Geo::Dashboard::User::Settings->setting_get({
                        set_name => 'gps/path',
                    });
?>

function geodu_settings( form ) {
// --------------------------------------------------
    var gps_location = $(form["gps_location"]).val();
    setting_save("gps_location",gps_location);
    $('#dialog').dialog('close');
    return false;
}

</script>

<form id="dialog-form" class="form-dialog" action="#" method="post" onsubmit="return geodu_settings(this)" style="">

  <div class="ui-widget" id="dialog-error" style="display:none" >
    <div class="ui-state-error ui-corner-all"> 
      <p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
      <strong>Alert:</strong> <span id="dialog-error-message">ERROR!</a></p> 
    </div> 
  </div> 

  <div class="form-row">
    <label>GPS Source</label>
    <input type="text" name="gps_location" value="<?=$set_rec?$set_rec->{set_data}:'/actions/gps_location.json'?>"/> 
    <div style="font-size:10px">Usually a URL like /actions/gps_location.json</div>
  </div>
</form>

